version = 5.2.2
archive_dir = /etc/letsencrypt/archive/findsmovies.com
cert = /etc/letsencrypt/live/findsmovies.com/cert.pem
privkey = /etc/letsencrypt/live/findsmovies.com/privkey.pem
chain = /etc/letsencrypt/live/findsmovies.com/chain.pem
fullchain = /etc/letsencrypt/live/findsmovies.com/fullchain.pem
[renewalparams]
account = 861790981e70282ebb7378694ac6d9d7
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
findsmovies.com = /var/www/certbot
www.findsmovies.com = /var/www/certbot
